name: app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_messaging: ^7.0.3
  flutter_staggered_grid_view: ^0.3.0
  rubber: ^0.3.2
  pin_code_text_field: ^1.6.0
  country_code_picker: ^1.1.5
  http: any
  flutter_rating_bar: ^1.3.0+1
  intl: any
  numberpicker: ^1.0.0
  flare_splash_screen: ^2.1.2
  flutter_svg: ^0.19.0
  shared_preferences: ^0.5.12+2
  meta: ^1.1.8
  equatable: ^1.2.5
  flutter_bloc: ^6.0.6
  flutter_cache_manager: ^2.0.0
  formz: ^0.2.0
  easy_localization: ^2.3.3
  flutter_widget_from_html: ^0.5.1+5
  url_launcher: ^5.7.10
  # flutter_inappwebview: ^4.0.0+4
  # flutter_webview_plugin: ^0.3.11
  webview_flutter: ^1.0.7
  auto_size_text: ^2.1.0
  flutter_swiper: ^1.1.6
  badges: ^1.1.6
  # requests: ^3.3.0
  graphql_flutter: ^3.1.0
  fluttertoast: ^7.1.6
  pull_to_refresh: ^1.6.3
  animations: ^1.1.2
  salomon_bottom_bar: ^2.0.0
  persistent_bottom_nav_bar: any
  expandable_bottom_bar: ^1.0.2
  flutter_launcher_icons: ^0.7.5
  # bottom_bar_with_sheet: ^0.5.4
  uni_links: ^0.4.0
  device_info: ^1.0.0

  flutter_localizations:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
  intl_translation: ^0.17.10+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon_hilia_3_1.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
  - assets/
  - assets/icons/
  - assets/translations/
  - assets/images/app_icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/Montserrat-Regular.ttf
  - family: NunitoSans
    fonts:
    - asset: fonts/NunitoSans-Regular.ttf

